BugTrackerWeb/Pages/ProjectOwnerView/PendingRequests.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.RequestItems.Queries.GetPendingRequestItems;
using Application.RequestItems.Queries.GetRequestItemDetails;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.ViewFeatures;

namespace WebUI.Pages.ProjectOwnerView
{
    public class PendingRequestsModel : PageModel
    {
        private readonly IMediator _mediator;
        public PendingRequestsModel(IMediator mediator)
        {
            _mediator = mediator;
        }

        [BindProperty]
        public GetPendingRequestItemsQuery GetPendingRequestItemsQuery { get; set; }

        [BindProperty]
        public PendingRequestItemsListVm PendingRequestItemsListVm { get; set; }

        public async Task OnGet()
        {
            PendingRequestItemsListVm = await _mediator.Send(new GetPendingRequestItemsQuery());
        }

        public async Task<PartialViewResult> OnGetRequestItemDetails(int id)
        {
            var requestList = await _mediator.Send(new GetRequestItemDetailsQuery { RequestId = id });
            var singleRequest = requestList.Requests.FirstOrDefault();

            return new PartialViewResult
            {
                ViewName = "UserView/_RequestItemDetails",
                ViewData = new ViewDataDictionary<PendingRequestItemDto>(ViewData, singleRequest)
            };

        }
    }
}

BugTrackerWeb/Pages/ProjectOwnerView/TicketDetails.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Application.Tickets.Command.AddComment;
using Application.Tickets.Queries.GetTicketDetails;
using BugTracker.Models.TicketProperties;
using BugTracker.PageManagers;
using BugTracker.Persistance;
using BugTracker.Persistance.Abstract;
using BugTracker.Utils;
using Domain.Entities;
using Domain.Entities.Roles;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BugTrackerWeb.Pages.ProjectOwnerView
{
    public class TicketDetailsModel : PageModel
    {
        //Remove this line
        private readonly IProjectPersistance _pp;
        private readonly ITicketManager _itm;
        private readonly IRequestPersistance _rp;
        private readonly ITicketPersistance _tp;
        private readonly IMediator _mediator;
        public TicketDetailsModel(IProjectPersistance pp,ITicketManager itm, IRequestPersistance rp,ITicketPersistance tp,IMediator mediator)
        {
            _itm = itm;
            _pp = pp;
            _rp = rp;
            _tp = tp;
            _mediator = mediator;
            //This assignment have to be changed!!!
            //TicketCatDDLOptions = new SelectList(EnumUtil.GetValues<TicketCategory>());
        }

        [BindProperty]
        public RequestItem Request { get; set; }

        [BindProperty]
        public Ticket Ticket { get; set; }

        [BindProperty]
        public Project Project { get; set; }

        [BindProperty]
        public int ProjectId { get; set; }

        [BindProperty]
        public int RequestId { get; set; }

        [BindProperty]
        public ICollection<QA> AvailableQAs { get; set; }
        
        [BindProperty]
        public int QAId { get; set; }

        public SelectList TicketCatDDLOptions { get; set; }
        public SelectList TicketPriorDDLOptions { get; set; }
        public SelectList TicketStatDDLOptions { get; set; }

        public List<SelectListItem> QAsList { get; set; }

        public void OnGetRequestDetails(int projectId, int requestId)
        {
            //Check if FromQuery works
            //Checked and works
            //Rather than getting this request from requests pool, try to get it from projects pool in the future
            Request = _rp.GetById(requestId);
            Project = _pp.Get(projectId);
            ProjectId = Project.Id;
            RequestId = requestId;

            AvailableQAs = Project.QAs.ToList();

            QAsList = AvailableQAs.Select(qa => new SelectListItem
            {
                Value = qa.Id.ToString(),
                Text = qa.Name
            }).ToList();

            TicketCatDDLOptions = new SelectList(EnumUtil.GetValues<TicketCategory>());
            TicketPriorDDLOptions = new SelectList(EnumUtil.GetValues<TicketPriority>());
            TicketStatDDLOptions = new SelectList(EnumUtil.GetValues<TicketStatus>());
        }

        /**
         * This is version with razor forms
         * 
         */
        public async Task<IActionResult> OnPostAssignTicketFromForm()
        {

            if (!ModelState.IsValid)
            {
                return RedirectToPage($"/ProjectOwnerView/");

            }
            await _itm.AssignTicket(RequestId, Ticket);

            return RedirectToPage($"/ProjectOwnerView/Index");
        }
        /**
         * AJAX call for assignmnent 
         */
        public async Task<JsonResult> OnPostAssignTicket(int qaId, int ticketId)
        {
            _itm.AssignToQa(ticketId, qaId);

            //Validation here is required, implement it later
            return new JsonResult(new { success = true, message = "Ticket has been assigned!", errormessage = "Something went wrong, try again later" });

            //This Url.Action should be considered as a return type
            //return new JsonResult(new { redirectToUrl = Url.Action("action", "contoller") });

        }


        //***********************************************//

        [BindProperty]
        public TicketDetailsVm TicketDetailsVm { get; set; }

        [BindProperty]
        public AddCommentCommand AddCommentCommand { get; set; } = new AddCommentCommand();

        public int TicketId { get; set; }
        public async Task OnGet(int ticketId)
        {
            TicketDetailsVm = await _mediator.Send(new GetTicketDetailsQuery { TicketId = ticketId });
        }

        public async Task<IActionResult> OnPost()
        {
            await _mediator.Send(AddCommentCommand);
            return RedirectToPage("/ProjectOwnerView/TicketDetails",new { ticketId=AddCommentCommand.TicketId });
        }

    }
}

BugTrackerWeb/Pages/UserView/CreateRequest.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BugTracker.DB;
using BugTracker.Models;
using BugTracker.Persistance;
using BugTracker.Persistance.Abstract;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BugTrackerWeb.Pages.UserView
{
    public class CreateTicketModel : PageModel
    {
        private readonly AppDbContext _ctx;
        private readonly IRequestPersistance _rp;
        private readonly IProjectPersistance _pp;
        private readonly ITicketPersistance _tp;
        public CreateTicketModel(AppDbContext context, IRequestPersistance rp, IProjectPersistance pp, ITicketPersistance tp)
        {
            _ctx = context;
            _rp = rp;
            _pp = pp;
            _tp = tp;
        }


        [BindProperty]
        public Request NewRequest { get; set; }

        [BindProperty]
        public int ProjectId { get; set; }

        [BindProperty]
        public List<SelectListItem> ProjectListDDL { get; set; }


        public void OnGet()
        {
            ProjectListDDL = PopulateProjectList();
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                AssignUserToRequest();
                await _rp.SaveAsync(NewRequest);
                return RedirectToPage("Index");
            }
            else
            {
                return Page();
            }
        }

        public void AssignUserToRequest()
        {
            NewRequest.Author = User.Identity.Name;
        }

        //Maybe it could be generic at some point?
        public List<SelectListItem> PopulateProjectList()
        {

            return _pp.GetAll().Select(p => new SelectListItem
            {
                Value = p.Id.ToString(),
                Text = p.Name

            }).ToList();
        }
    }
}

BugTrackerWeb/Pages/UserView/DeleteRequest.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BugTracker.Persistance.Abstract;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BugTrackerWeb.Pages.UserView
{
    public class DeleteRequestModel : PageModel
    {
        private readonly IRequestPersistance _rp;
        public DeleteRequestModel(IRequestPersistance rp)
        {
            _rp = rp;
        }

        public async Task<JsonResult> OnPostDelete(int id)
        {
                var reqToDelete = await _rp.GetByIdAsync(id);
                if (reqToDelete == null)
                {
                    return new JsonResult(new { success = false, message = "Error while Deleting" });

                }
                await _rp.DeleteAsync(reqToDelete);
                return new JsonResult(new { success = true, message = "Delete successful" });

        }

    }
}

BugTrackerWeb/Pages/UserView/EditRequest.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.RequestItems.Commands.EditRequestItem;
using Application.RequestItems.Queries.GetEditRequestItem;
using BugTracker.Persistance;
using BugTracker.Persistance.Abstract;
using Domain.Entities;
using Infrastructure.Persistance;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BugTrackerWeb.Pages.UserView
{
    public class EditTicketModel : PageModel
    {
        private readonly IMediator _mediator;

        public EditTicketModel(IMediator mediator)
        {
            _mediator = mediator;

        }
        [BindProperty]
        public EditRequestItemVm EditRequestItemVm { get; set; }

        [BindProperty]
        public EditRequestItemCommand EditRequestItemCommand { get; set; }

        public async Task OnGet(int id)
        {
            EditRequestItemVm = await _mediator.Send(new GetEditRequestItemQuery { Id = id });
        }

        public async Task<IActionResult> OnPost()
        {
            await _mediator.Send(EditRequestItemCommand);
            return RedirectToPage("PendingRequests");

        }


    }
}

BugTrackerWeb/Pages/UserView/InProcessRequests.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.RequestItems.Queries.GetInProcessRequestItemDetails;
using Application.RequestItems.Queries.GetInProcessRequestItems;
using BugTracker.Persistance;
using Domain.Entities;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.ViewFeatures;

namespace BugTrackerWeb.Pages.UserView
{
    public class InProcessRequestsModel : PageModel
    {
        private readonly IMediator mediator;
        private readonly ITicketPersistance _tp;
        public InProcessRequestsModel(IMediator mediator, ITicketPersistance tp)
        {
            this.mediator = mediator;
        }
        //[BindProperty]
        //public List<Ticket> Tickets { get; set; }

        [BindProperty]
        public Ticket CheckedTicket { get; set; }

        //[BindProperty]
        //public GetInProcessRequestItemsQuery GetInProcessRequestItemsQuery { get; set; }

        [BindProperty]
        public InProcessRequestItemsVm InProcessRequestItemsVm { get; set; }

        public async Task OnGet()
        {
            InProcessRequestItemsVm = await mediator.Send(new GetInProcessRequestItemsQuery());

        }

        public async Task<PartialViewResult> OnGetTicketDetails(int id)
        {
            InProcessRequestItemsVm = await mediator.Send(new GetInProcessRequestItemDetailsQuery { TicketId = id });

            return new PartialViewResult
            {
                ViewName = "_InProcessTicketDetails",
                ViewData = new ViewDataDictionary<InProcessRequestItemsVm>(ViewData, InProcessRequestItemsVm)
            };
        }
    }
}

BugTrackerWeb/Pages/UserView/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using BugTracker.Persistance;
using BugTracker.Persistance.Abstract;
using Domain.Entities;
using Infrastructure.Persistance;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BugTrackerWeb.Pages.UserView
{

    [Authorize]
    public class IndexModel : PageModel
    {
        public IndexModel()
        {
        }
    }
}

BugTrackerWeb/Pages/UserView/NewRequest.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Application.Common.Interfaces;
using Application.RequestItems.Commands.CreateRequestItem;
using Application.RequestItems.GetNewRequestItem;
using Application.RequestItems.Queries.GetNewRequestItem;
using BugTracker.Persistance;
using BugTracker.Persistance.Abstract;
using Domain.Entities;
using Infrastructure.Persistance;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.DependencyInjection;

namespace BugTrackerWeb.Pages.UserView
{
    public class NewRequestModel : PageModel
    {
        private readonly IMediator _mediator;


        public NewRequestModel(IMediator mediator)
        {
            _mediator = mediator;
        }

        [BindProperty]
        public NewRequestItemVm NewRequestItemVm { get; set; }

        [BindProperty]
        public CreateRequestItemCommand CreateRequestItemCommand { get; set; }
        public async Task OnGetAsync()
        {

            NewRequestItemVm = await _mediator.Send(new GetNewRequestItemQuery());

        }
        public async Task<IActionResult> OnPostSaveRequest()
        {
            await _mediator.Send(CreateRequestItemCommand);
            return RedirectToPage("/UserView/PendingRequests");
        }
    }


}

BugTrackerWeb/Pages/UserView/PendingRequests.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.RequestItems.Commands.DeleteRequestItem;
using Application.RequestItems.Queries.GetPendingRequestItems;
using BugTracker.Persistance.Abstract;
using Domain.Entities;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.Extensions.Caching.Memory;
using Newtonsoft.Json;

namespace BugTrackerWeb.Pages.UserView
{
    public class PendingRequestModel : PageModel
    {
        private readonly IMediator _mediator;
        private readonly IMemoryCache _cache;

        public PendingRequestModel(IMediator mediator,IMemoryCache cache)
        {
            _mediator = mediator;
            _cache = cache;
        }

        public GetPendingRequestItemsQuery GetPendingRequestItemsQuery { get; set; }

        public PendingRequestItemsListVm PendingRequestItemsListVm { get; set; }


        public async Task OnGet()
        {
            PendingRequestItemsListVm = await _mediator.Send(new GetPendingRequestItemsQuery());
            _cache.Set("RequestItems", JsonConvert.SerializeObject(PendingRequestItemsListVm.Requests));

        }


        public async Task<PartialViewResult> OnGetRequestItemDetails(int id)
        {
            IList<PendingRequestItemDto> requests = JsonConvert.DeserializeObject<List<PendingRequestItemDto>>(_cache.Get("RequestItems").ToString());

            PendingRequestItemDto request = requests.Where(r => r.Id == id)
                .FirstOrDefault();

            return new PartialViewResult
            {
                ViewName = "_RequestItemDetails",
                ViewData = new ViewDataDictionary<PendingRequestItemDto>(ViewData, request)
            };

        }

        public async Task<JsonResult> OnPostDelete(int id)
        {
            return await _mediator.Send(new DeleteRequestItemCommand { Id = id });

        }




        //public async Task<JsonResult> OnGetPopulateTable()
        //{
        //    var requests = await _rp.GetCreatedByAuthorAsync(User.Identity.Name);
        //    var data = RequestModelView.CreateModelView(requests);

        //    return new JsonResult(new { data });
        //}

    }

    //public class RequestModelView
    //{
    //    public int Id { get; set; }
    //    public string Title { get; set; }
    //    public string Description { get; set; }
    //    public string Project { get; set; }
    //    private static IEnumerable<RequestModelView> Transform(List<RequestItem> requests)
    //    {
    //        foreach (var r in requests)
    //        {
    //            yield return new RequestModelView { Id = r.Id, Title = r.Title, Project = r.Project.Name };
    //        }
    //    }

    //    public static List<RequestModelView> CreateModelView(List<RequestItem> requests)
    //    {
    //        return Transform(requests).ToList();
    //    }
    //}
}

BugTrackerWeb/Pages/UserView/CreateRequest.cshtml
@page
@model BugTrackerWeb.Pages.UserView.CreateTicketModel
@{
}
<br />
<h2 class="text-info">Create New Request</h2>
<div class="border container" style="padding:30px;">
    <form method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="NewRequest.Title"></label>
            </div>
            <div class="col-6">
                <input asp-for="NewRequest.Title" class="form-control" />
            </div>
            <span asp-validation-for="NewRequest.Title" class="text-danger field-validation-valid">Required</span>
        </div>
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="NewRequest.Description"></label>
            </div>
            <div class="col-6">
                <input asp-for="NewRequest.Description" class="form-control" />
            </div>
            <span asp-validation-for="NewRequest.Description" class="text-danger field-validation-valid">Required</span>
        </div>

        <div class="form-group row">
            <div class="col-4">
                <label asp-for="NewRequest.ProjectId">Project name</label>
            </div>
            <div class="col-6">
                <select asp-for="NewRequest.ProjectId" class="form-control" asp-items="@Model.ProjectListDDL"></select>
            </div>
            <div>
                <span asp-validation-for="ProjectId" class="text-danger field-validation-valid">Project ID required</span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-3 offset-4">
                <input type="submit" value="Create" class="btn btn-primary form-control" />
            </div>
            <div class="col-3">
                <a asp-for="Index" class="btn btn-success form-control">Back to the dashboard</a>
            </div>
        </div>

    </form>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

BugTrackerWeb/Pages/UserView/DeleteRequest.cshtml
@page
@model BugTrackerWeb.Pages.UserView.DeleteRequestModel
@{
}
@section Scripts{
    <script src="~/js/UserView/pendingReq.js"></script>

}

BugTrackerWeb/Pages/UserView/EditRequest.cshtml
@page
@model BugTrackerWeb.Pages.UserView.EditTicketModel
@{

    <br />
    <h2 class="text-info">Update ticket</h2>
    <div class="border container" style="padding:30px;">
        <form method="post">
            <input type="hidden" asp-for="@Model.EditRequestItemCommand.Id" value="@Model.EditRequestItemVm.Id" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <!--Title start-->
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="EditRequestItemCommand.Title"></label>
                </div>
                <div class="col-6">
                    <input asp-for="EditRequestItemCommand.Title" class="form-control" />
                </div>
            </div>
            <!--Title end-->
            <!--StepToReproduce start-->
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="EditRequestItemCommand.StepsToReproduce"></label>
                </div>
                <div class="col-6">
                    <input asp-for="EditRequestItemCommand.StepsToReproduce" class="form-control" />
                </div>
            </div>
            <!--StepToReproduce end-->
            <!--ExpectedResult start-->
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="EditRequestItemCommand.ExpectedResult"></label>
                </div>
                <div class="col-6">
                    <input asp-for="EditRequestItemCommand.ExpectedResult" class="form-control" />
                </div>
            </div>
            <!--ExpectedResult end-->
            <!--ActualResult start-->
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="EditRequestItemCommand.ActualResult"></label>
                </div>
                <div class="col-6">
                    <input asp-for="EditRequestItemCommand.ActualResult" class="form-control" />
                </div>
            </div>
            <!--ActualResult end-->
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="EditRequestItemCommand.ProjectId">Project name</label>
                </div>
                <div class="col-6">
                    <select asp-for="EditRequestItemCommand.ProjectId" class="form-control" asp-items='@new SelectList(Model.EditRequestItemVm.AvailableProjects,"Key","Value")'></select>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3 offset-4">
                    <input type="submit" value="Update" class="btn btn-primary form-control" />
                </div>
                <div class="col-3">
                    <a asp-for="Index" class="btn btn-success form-control">Back to the dashboard</a>
                </div>
            </div>
        </form>
    </div>

    @section Scripts{
        <partial name="_ValidationScriptsPartial" />
    }
}

BugTrackerWeb/Pages/UserView/InProcessRequests.cshtml
@page
@model BugTrackerWeb.Pages.UserView.InProcessRequestsModel
<link rel="stylesheet" href="~/css/projectdetails.css" />

@{
    <h2 class="text-info">Requests in process</h2>

    <div class="row">
        <div class="col-8">
            @if (Model.InProcessRequestItemsVm.InProcessRequests.Count() > 0)
            {
                <table id="requestsTable" class="table table-striped border table-sm">
                    <tr class="table-secondary">
                        <th>
                            <label asp-for="InProcessRequestItemsVm.InProcessRequests.FirstOrDefault().Title"></label>
                        </th>
                        <th>
                            <label asp-for="InProcessRequestItemsVm.InProcessRequests.FirstOrDefault().TicketStatus"></label>
                        </th>
                    </tr>
                    @foreach (var item in Model.InProcessRequestItemsVm.InProcessRequests)
                    {
                        <tr class="clickable-row">
                            <td>
                                @Html.DisplayFor(m => item.Title)
                            </td>
                            <td>
                                @Html.DisplayFor(m => item.TicketStatus)
                            </td>
                            <td>
                                <button data-requestid="@item.Id" class="btn btn-success btn-sm text-white show-details">Details</button>
                            </td>
                        </tr>
                    }
                </table>
            }
            else
            {
                <p>You don't have any tickets in processing</p>
            }
        </div>
        <div class="col-sm">
            <h3 class="text-info">Request details</h3>
            <article id="ticketDetails">
                <span class="text-info">You haven't select any requet yet</span>
            </article>
        </div>
    </div>
}

@section Scripts{
    <script src="~/js/UserView/inProcessReq.js"></script>
}

BugTrackerWeb/Pages/UserView/Index.cshtml
@page
@model BugTrackerWeb.Pages.UserView.IndexModel
@{
<section id="usercontent">
    <h1 class="text-info">Dashboard</h1>
    <br />
    <div class="container row p-0 m0">
        <div class="col-6">
            <span class="text-info">Dashboard has not been implemented yet!</span>
        </div>
    </div>
</section>

}

BugTrackerWeb/Pages/UserView/NewRequest.cshtml
@page
@model BugTrackerWeb.Pages.UserView.NewRequestModel
@{
}
<br />
<h2 class="text-info">Create New Request</h2>
<div class="border container" style="padding:30px;">
    <form method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <!--Title input START-->
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="CreateRequestItemCommand.Title"></label>
            </div>
            <div class="col-6">
                <input asp-for="CreateRequestItemCommand.Title" class="form-control" />
            </div>
            <span asp-validation-for="CreateRequestItemCommand.Title" class="text-danger field-validation-valid">Required</span>
        </div>
        <!--Title input END-->
        <!--Step to reproduce input START-->
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="CreateRequestItemCommand.StepToReproduce"></label>
            </div>
            <div class="col-6">
                <textarea asp-for="CreateRequestItemCommand.StepToReproduce" class="form-control"></textarea>
            </div>
            <span asp-validation-for="CreateRequestItemCommand.StepToReproduce" class="text-danger field-validation-valid">Required</span>
        </div>
        <!--Step to reproduce input END-->
        <!--Expected result input START-->
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="CreateRequestItemCommand.ExpectedResult"></label>
            </div>
            <div class="col-6">
                <textarea asp-for="CreateRequestItemCommand.ExpectedResult" class="form-control"></textarea>
            </div>
            <span asp-validation-for="CreateRequestItemCommand.ExpectedResult" class="text-danger field-validation-valid">Required</span>
        </div>
        <!--Expected result input END-->
        <!--Actual result input START-->
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="CreateRequestItemCommand.ActualResult"></label>
            </div>
            <div class="col-6">
                <textarea asp-for="CreateRequestItemCommand.ActualResult" class="form-control"></textarea>
            </div>
            <span asp-validation-for="CreateRequestItemCommand.ActualResult" class="text-danger field-validation-valid">Required</span>
        </div>
        <!--Actual result input END-->
        <!--Project id input START-->
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="CreateRequestItemCommand.ProjectId">Project name</label>
            </div>
            <div class="col-6">
                <select asp-for="CreateRequestItemCommand.ProjectId" class="form-control" asp-items='@new SelectList(Model.NewRequestItemVm.AvailableProjects,"Key","Value")'></select>
            </div>
            <div>
                <span asp-validation-for="CreateRequestItemCommand.ProjectId" class="text-danger field-validation-valid">Project ID required</span>
            </div>
        </div>
        <!--Project id input END-->
        <div class="form-group row">
            <div class="col-3 offset-4">
                <button asp-page-handler="SaveRequest" class="btn btn-success form-control">Create</button>
            </div>
            <div class="col-3">
                <a asp-page="Index" class="btn btn-info form-control">Back to the dashboard</a>
            </div>
        </div>

    </form>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

BugTrackerWeb/Pages/UserView/_InProcessTicketDetails.cshtml
@model Application.RequestItems.Queries.GetInProcessRequestItems.InProcessRequestItemsVm
@{
    <h6>Title</h6>
    <span>@Model.InProcessRequests.FirstOrDefault().Title</span>

    <h6>Created at</h6>
    <span>@Model.InProcessRequests.FirstOrDefault().Created</span>

    <h6>Project name</h6>
    <span>@Model.InProcessRequests.FirstOrDefault().ProjectName</span>

}

BugTrackerWeb/Pages/UserView/_RequestItemDetails.cshtml
@model Application.RequestItems.Queries.GetPendingRequestItems.PendingRequestItemDto
@{

    <h6>Ticket title</h6>
    <span>@Model.Title</span>

    <h5>Steps to reproduce</h5>
    <span>@Model.StepsToReproduce</span>

    <h6>Expected results</h6>
    <span>@Model.ExpectedResult</span>

    <h6>Actual results</h6>
    <span>@Model.ActualResult</span>

    @if (User.IsInRole("ProjectOwner"))
    {
        <h6>Author</h6>
        <span>@Model.Author</span>
    }

}

BugTrackerWeb/Pages/UserView/_TicketDetails.cshtml
@model BugTracker.Models.Ticket
@{
    <label><b>Title</b></label>
    <br />
    <tr>@Model.Title</tr>
    <br />
    <label><b>Description</b></label>
    <br />
    <tr>@Model.Description</tr>
    <br />
    <br />
    <label><b>Category</b></label>
    <tr>@Model.TicketCategory</tr>
    <br />
    <label><b>Ticket status</b></label>
    <tr>@Model.TicketStatus</tr>
    <br />
    <label><b>Ticket priority</b></label>
    <tr>@Model.TicketCategory</tr>

}